### ISSUE TITLE
Biome chunk borders

### ISSUE THREAD

**Issue by A-T-L-A-S** [paulevsGitch/EdenRing#39]
![grafik](https://user-images.githubusercontent.com/39281662/175810058-0c1f728e-d958-4bdf-8793-08c942223a49.png)

I hope this is not a mod incompatibility. I will test this and update this issue accordingly.
1.18.2
Fabric - 0.14.8
Edenring - 0.5.2

**Comment by paulevsGitch** [comment]
This issue is related to Eden world generation (or more precisely to changes in noise between 1.18.1 and 1.18.2). It is possible to fix, but will require some hard work, and fix will be probably available only for 1.19+ version. If you are playing on 1.18.2 version you can use worldedit and regenerate wrong chunks after rejoining world - it should fix it

**Comment by paulevsGitch** [comment]
> But how do I know which chunks are "Wrong" 

Visually, they are obviously different from normal chunks

**Comment by NobleDraconian** [comment]
This is still happening with eden ring 0.6.4 for minecraft 1.19.2:
![image](https://github.com/paulevsGitch/EdenRing/assets/26460940/6524c537-02d4-435a-8314-d3854355c5e4)

**Comment by paulevsGitch** [comment]
Yes since it was not fixed
